// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sizjrgwifgwemfpavgcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpempyZ3dpZmd3ZW1mcGF2Z2NzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NjkxNDYsImV4cCI6MjA2OTQ0NTE0Nn0.5F1Y21TCCBP63AZh20QLGfAH9qeKFf8h1PV4t1ZNS3c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});